import { Suspense } from "react";
import { Geist, Geist_Mono } from "next/font/google";

import "./globals.css";
import { LoadingProvider } from "@context/LoadingProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <LoadingProvider>
      <Suspense>
        <html lang="en">
          <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
          >
            {children}
          </body>
        </html>
      </Suspense>
    </LoadingProvider>
  );
}
